language: node_js
node_js:
  - "6.4"
before_script:
  - npm install grunt-cli -g
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
    
